/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ReadRegionsRequest,
    ReadRegionsRequestFromJSON,
    ReadRegionsRequestToJSON,
    ReadRegionsResponse,
    ReadRegionsResponseFromJSON,
    ReadRegionsResponseToJSON,
} from '../models';

export interface ReadRegionsOperationRequest {
    readRegionsRequest?: ReadRegionsRequest;
}

/**
 * RegionApi - interface
 * 
 * @export
 * @interface RegionApiInterface
 */
export interface RegionApiInterface {
    /**
     * 
     * @param {ReadRegionsRequest} [readRegionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApiInterface
     */
    readRegionsRaw(requestParameters: ReadRegionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<ReadRegionsResponse>>;

    /**
     */
    readRegions(requestParameters: ReadRegionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<ReadRegionsResponse>;

}

/**
 * 
 */
export class RegionApi extends runtime.BaseAPI implements RegionApiInterface {

    /**
     */
    async readRegionsRaw(requestParameters: ReadRegionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<ReadRegionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';



        const body: any = ReadRegionsRequestToJSON(requestParameters.readRegionsRequest);

        const request: runtime.RequestOpts = {
            path: `/ReadRegions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: body,
        }
        if (this.configuration && this.configuration.awsV4SignerParameters) {
            const SignUrl = this.configuration.basePath + request.path;
            const SignBody = JSON.stringify(request.body);
            const signer = new runtime.AwsV4Signer(this.configuration.awsV4SignerParameters);
            const signResult = await signer.sign('POST', SignUrl, headerParameters, SignBody);
            //request.url = signResult.url;
            //request.method = signResult.method;
            request.headers = signResult.headers;
        }
        const response = await this.request(request, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadRegionsResponseFromJSON(jsonValue));
    }

    /**
     */
    async readRegions(requestParameters: ReadRegionsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<ReadRegionsResponse> {
        const response = await this.readRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
