/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.24
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the access key.
 * @export
 * @interface AccessKeySecretKey
 */
export interface AccessKeySecretKey {
    /**
     * The ID of the access key.
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    accessKeyId?: string;
    /**
     * The date and time (UTC) of creation of the access key.
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    creationDate?: string;
    /**
     * The date and time (UTC) at which the access key expires.
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    expirationDate?: string;
    /**
     * The date and time (UTC) of the last modification of the access key.
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    lastModificationDate?: string;
    /**
     * The access key that enables you to send requests.
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    secretKey?: string;
    /**
     * The state of the access key (`ACTIVE` if the key is valid for API calls, or `INACTIVE` if not).
     * @type {string}
     * @memberof AccessKeySecretKey
     */
    state?: string;
}

export function AccessKeySecretKeyFromJSON(json: any): AccessKeySecretKey {
    return AccessKeySecretKeyFromJSONTyped(json, false);
}

export function AccessKeySecretKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessKeySecretKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessKeyId': !exists(json, 'AccessKeyId') ? undefined : json['AccessKeyId'],
        'creationDate': !exists(json, 'CreationDate') ? undefined : json['CreationDate'],
        'expirationDate': !exists(json, 'ExpirationDate') ? undefined : json['ExpirationDate'],
        'lastModificationDate': !exists(json, 'LastModificationDate') ? undefined : json['LastModificationDate'],
        'secretKey': !exists(json, 'SecretKey') ? undefined : json['SecretKey'],
        'state': !exists(json, 'State') ? undefined : json['State'],
    };
}

export function AccessKeySecretKeyToJSON(value?: AccessKeySecretKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccessKeyId': value.accessKeyId,
        'CreationDate': value.creationDate,
        'ExpirationDate': value.expirationDate,
        'LastModificationDate': value.lastModificationDate,
        'SecretKey': value.secretKey,
        'State': value.state,
    };
}

