/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNetRequest
 */
export interface CreateNetRequest {
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof CreateNetRequest
     */
    dryRun?: boolean;
    /**
     * The IP range for the Net, in CIDR notation (for example, 10.0.0.0/16).
     * @type {string}
     * @memberof CreateNetRequest
     */
    ipRange: string;
    /**
     * The tenancy options for the VMs (`default` if a VM created in a Net can be launched with any tenancy, `dedicated` if it can be launched with dedicated tenancy VMs running on single-tenant hardware).
     * @type {string}
     * @memberof CreateNetRequest
     */
    tenancy?: string;
}

export function CreateNetRequestFromJSON(json: any): CreateNetRequest {
    return CreateNetRequestFromJSONTyped(json, false);
}

export function CreateNetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
        'ipRange': json['IpRange'],
        'tenancy': !exists(json, 'Tenancy') ? undefined : json['Tenancy'],
    };
}

export function CreateNetRequestToJSON(value?: CreateNetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DryRun': value.dryRun,
        'IpRange': value.ipRange,
        'Tenancy': value.tenancy,
    };
}

