/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';
import {
    Subnet,
    SubnetFromJSON,
    SubnetFromJSONTyped,
    SubnetToJSON,
} from './Subnet';

/**
 * 
 * @export
 * @interface CreateSubnetResponse
 */
export interface CreateSubnetResponse {
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof CreateSubnetResponse
     */
    responseContext?: ModelResponseContext;
    /**
     * 
     * @type {Subnet}
     * @memberof CreateSubnetResponse
     */
    subnet?: Subnet;
}

export function CreateSubnetResponseFromJSON(json: any): CreateSubnetResponse {
    return CreateSubnetResponseFromJSONTyped(json, false);
}

export function CreateSubnetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubnetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
        'subnet': !exists(json, 'Subnet') ? undefined : SubnetFromJSON(json['Subnet']),
    };
}

export function CreateSubnetResponseToJSON(value?: CreateSubnetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
        'Subnet': SubnetToJSON(value.subnet),
    };
}

