/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.26
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteApiAccessRuleRequest
 */
export interface DeleteApiAccessRuleRequest {
    /**
     * The ID of the API access rule you want to delete.
     * @type {string}
     * @memberof DeleteApiAccessRuleRequest
     */
    apiAccessRuleId: string;
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof DeleteApiAccessRuleRequest
     */
    dryRun?: boolean;
}

export function DeleteApiAccessRuleRequestFromJSON(json: any): DeleteApiAccessRuleRequest {
    return DeleteApiAccessRuleRequestFromJSONTyped(json, false);
}

export function DeleteApiAccessRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteApiAccessRuleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiAccessRuleId': json['ApiAccessRuleId'],
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
    };
}

export function DeleteApiAccessRuleRequestToJSON(value?: DeleteApiAccessRuleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ApiAccessRuleId': value.apiAccessRuleId,
        'DryRun': value.dryRun,
    };
}

