/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * One or more filters.
 * @export
 * @interface FiltersApiLog
 */
export interface FiltersApiLog {
    /**
     * The access keys used for the logged calls.
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    queryAccessKeys?: Array<string>;
    /**
     * The names of the APIs of the logged calls (always `oapi` for the OUTSCALE API).
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    queryApiNames?: Array<string>;
    /**
     * The names of the logged calls.
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    queryCallNames?: Array<string>;
    /**
     * The date after which you want to retrieve logged calls, in ISO 8601 format (for example, `2020-06-14`). By default, this date is set to 48 hours before the `QueryDateBefore` parameter value.
     * @type {Date}
     * @memberof FiltersApiLog
     */
    queryDateAfter?: Date;
    /**
     * The date before which you want to retrieve logged calls, in ISO 8601 format (for example, `2020-06-30`). By default, this date is set to now, or 48 hours after the `QueryDateAfter` parameter value.
     * @type {Date}
     * @memberof FiltersApiLog
     */
    queryDateBefore?: Date;
    /**
     * The IPs used for the logged calls.
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    queryIpAddresses?: Array<string>;
    /**
     * The user agents of the HTTP requests of the logged calls.
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    queryUserAgents?: Array<string>;
    /**
     * The request IDs provided in the responses of the logged calls.
     * @type {Array<string>}
     * @memberof FiltersApiLog
     */
    requestIds?: Array<string>;
    /**
     * The HTTP status codes of the logged calls.
     * @type {Array<number>}
     * @memberof FiltersApiLog
     */
    responseStatusCodes?: Array<number>;
}

export function FiltersApiLogFromJSON(json: any): FiltersApiLog {
    return FiltersApiLogFromJSONTyped(json, false);
}

export function FiltersApiLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltersApiLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queryAccessKeys': !exists(json, 'QueryAccessKeys') ? undefined : json['QueryAccessKeys'],
        'queryApiNames': !exists(json, 'QueryApiNames') ? undefined : json['QueryApiNames'],
        'queryCallNames': !exists(json, 'QueryCallNames') ? undefined : json['QueryCallNames'],
        'queryDateAfter': !exists(json, 'QueryDateAfter') ? undefined : (new Date(json['QueryDateAfter'])),
        'queryDateBefore': !exists(json, 'QueryDateBefore') ? undefined : (new Date(json['QueryDateBefore'])),
        'queryIpAddresses': !exists(json, 'QueryIpAddresses') ? undefined : json['QueryIpAddresses'],
        'queryUserAgents': !exists(json, 'QueryUserAgents') ? undefined : json['QueryUserAgents'],
        'requestIds': !exists(json, 'RequestIds') ? undefined : json['RequestIds'],
        'responseStatusCodes': !exists(json, 'ResponseStatusCodes') ? undefined : json['ResponseStatusCodes'],
    };
}

export function FiltersApiLogToJSON(value?: FiltersApiLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'QueryAccessKeys': value.queryAccessKeys,
        'QueryApiNames': value.queryApiNames,
        'QueryCallNames': value.queryCallNames,
        'QueryDateAfter': value.queryDateAfter === undefined ? undefined : (value.queryDateAfter.toISOString().substr(0,10)),
        'QueryDateBefore': value.queryDateBefore === undefined ? undefined : (value.queryDateBefore.toISOString().substr(0,10)),
        'QueryIpAddresses': value.queryIpAddresses,
        'QueryUserAgents': value.queryUserAgents,
        'RequestIds': value.requestIds,
        'ResponseStatusCodes': value.responseStatusCodes,
    };
}

