/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.20
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * One or more filters.
 * @export
 * @interface FiltersProductType
 */
export interface FiltersProductType {
    /**
     * The IDs of the product types.
     * @type {Array<string>}
     * @memberof FiltersProductType
     */
    productTypeIds?: Array<string>;
}

export function FiltersProductTypeFromJSON(json: any): FiltersProductType {
    return FiltersProductTypeFromJSONTyped(json, false);
}

export function FiltersProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltersProductType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productTypeIds': !exists(json, 'ProductTypeIds') ? undefined : json['ProductTypeIds'],
    };
}

export function FiltersProductTypeToJSON(value?: FiltersProductType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ProductTypeIds': value.productTypeIds,
    };
}

