/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * One or more filters.
 * @export
 * @interface FiltersApiAccessRule
 */
export interface FiltersApiAccessRule {
    /**
     * One or more IDs of API access rules.
     * @type {Array<string>}
     * @memberof FiltersApiAccessRule
     */
    apiAccessRuleIds?: Array<string>;
    /**
     * One or more IDs of Client Certificate Authorities (CAs).
     * @type {Array<string>}
     * @memberof FiltersApiAccessRule
     */
    caIds?: Array<string>;
    /**
     * One or more Client Certificate Common Names (CNs).
     * @type {Array<string>}
     * @memberof FiltersApiAccessRule
     */
    cns?: Array<string>;
    /**
     * One or more descriptions of API access rules.
     * @type {Array<string>}
     * @memberof FiltersApiAccessRule
     */
    descriptions?: Array<string>;
    /**
     * One or more IP ranges, in CIDR notation (for example, 192.0.2.0/16).
     * @type {Array<string>}
     * @memberof FiltersApiAccessRule
     */
    ipRanges?: Array<string>;
}

export function FiltersApiAccessRuleFromJSON(json: any): FiltersApiAccessRule {
    return FiltersApiAccessRuleFromJSONTyped(json, false);
}

export function FiltersApiAccessRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiltersApiAccessRule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiAccessRuleIds': !exists(json, 'ApiAccessRuleIds') ? undefined : json['ApiAccessRuleIds'],
        'caIds': !exists(json, 'CaIds') ? undefined : json['CaIds'],
        'cns': !exists(json, 'Cns') ? undefined : json['Cns'],
        'descriptions': !exists(json, 'Descriptions') ? undefined : json['Descriptions'],
        'ipRanges': !exists(json, 'IpRanges') ? undefined : json['IpRanges'],
    };
}

export function FiltersApiAccessRuleToJSON(value?: FiltersApiAccessRule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ApiAccessRuleIds': value.apiAccessRuleIds,
        'CaIds': value.caIds,
        'Cns': value.cns,
        'Descriptions': value.descriptions,
        'IpRanges': value.ipRanges,
    };
}

