/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.22
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the flexible GPU (fGPU).
 * @export
 * @interface FlexibleGpu
 */
export interface FlexibleGpu {
    /**
     * If true, the fGPU is deleted when the VM is terminated.
     * @type {boolean}
     * @memberof FlexibleGpu
     */
    deleteOnVmDeletion?: boolean;
    /**
     * The ID of the fGPU.
     * @type {string}
     * @memberof FlexibleGpu
     */
    flexibleGpuId?: string;
    /**
     * The compatible processor generation.
     * @type {string}
     * @memberof FlexibleGpu
     */
    generation?: string;
    /**
     * The model of fGPU. For more information, see [About Flexible GPUs](https://docs.outscale.com/en/userguide/About-Flexible-GPUs.html).
     * @type {string}
     * @memberof FlexibleGpu
     */
    modelName?: string;
    /**
     * The state of the fGPU (`allocated` \| `attaching` \| `attached` \| `detaching`).
     * @type {string}
     * @memberof FlexibleGpu
     */
    state?: string;
    /**
     * The Subregion where the fGPU is located.
     * @type {string}
     * @memberof FlexibleGpu
     */
    subregionName?: string;
    /**
     * The ID of the VM the fGPU is attached to, if any.
     * @type {string}
     * @memberof FlexibleGpu
     */
    vmId?: string;
}

export function FlexibleGpuFromJSON(json: any): FlexibleGpu {
    return FlexibleGpuFromJSONTyped(json, false);
}

export function FlexibleGpuFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlexibleGpu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deleteOnVmDeletion': !exists(json, 'DeleteOnVmDeletion') ? undefined : json['DeleteOnVmDeletion'],
        'flexibleGpuId': !exists(json, 'FlexibleGpuId') ? undefined : json['FlexibleGpuId'],
        'generation': !exists(json, 'Generation') ? undefined : json['Generation'],
        'modelName': !exists(json, 'ModelName') ? undefined : json['ModelName'],
        'state': !exists(json, 'State') ? undefined : json['State'],
        'subregionName': !exists(json, 'SubregionName') ? undefined : json['SubregionName'],
        'vmId': !exists(json, 'VmId') ? undefined : json['VmId'],
    };
}

export function FlexibleGpuToJSON(value?: FlexibleGpu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DeleteOnVmDeletion': value.deleteOnVmDeletion,
        'FlexibleGpuId': value.flexibleGpuId,
        'Generation': value.generation,
        'ModelName': value.modelName,
        'State': value.state,
        'SubregionName': value.subregionName,
        'VmId': value.vmId,
    };
}

