/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OsuExportImageExportTask,
    OsuExportImageExportTaskFromJSON,
    OsuExportImageExportTaskFromJSONTyped,
    OsuExportImageExportTaskToJSON,
} from './OsuExportImageExportTask';
import {
    ResourceTag,
    ResourceTagFromJSON,
    ResourceTagFromJSONTyped,
    ResourceTagToJSON,
} from './ResourceTag';

/**
 * Information about the OMI export task.
 * @export
 * @interface ImageExportTask
 */
export interface ImageExportTask {
    /**
     * If the OMI export task fails, an error message appears.
     * @type {string}
     * @memberof ImageExportTask
     */
    comment?: string;
    /**
     * The ID of the OMI to be exported.
     * @type {string}
     * @memberof ImageExportTask
     */
    imageId?: string;
    /**
     * 
     * @type {OsuExportImageExportTask}
     * @memberof ImageExportTask
     */
    osuExport?: OsuExportImageExportTask;
    /**
     * The progress of the OMI export task, as a percentage.
     * @type {number}
     * @memberof ImageExportTask
     */
    progress?: number;
    /**
     * The state of the OMI export task (`pending/queued` \| `pending` \| `completed` \| `failed` \| `cancelled`).
     * @type {string}
     * @memberof ImageExportTask
     */
    state?: string;
    /**
     * One or more tags associated with the image export task.
     * @type {Array<ResourceTag>}
     * @memberof ImageExportTask
     */
    tags?: Array<ResourceTag>;
    /**
     * The ID of the OMI export task.
     * @type {string}
     * @memberof ImageExportTask
     */
    taskId?: string;
}

export function ImageExportTaskFromJSON(json: any): ImageExportTask {
    return ImageExportTaskFromJSONTyped(json, false);
}

export function ImageExportTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageExportTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'Comment') ? undefined : json['Comment'],
        'imageId': !exists(json, 'ImageId') ? undefined : json['ImageId'],
        'osuExport': !exists(json, 'OsuExport') ? undefined : OsuExportImageExportTaskFromJSON(json['OsuExport']),
        'progress': !exists(json, 'Progress') ? undefined : json['Progress'],
        'state': !exists(json, 'State') ? undefined : json['State'],
        'tags': !exists(json, 'Tags') ? undefined : ((json['Tags'] as Array<any>).map(ResourceTagFromJSON)),
        'taskId': !exists(json, 'TaskId') ? undefined : json['TaskId'],
    };
}

export function ImageExportTaskToJSON(value?: ImageExportTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Comment': value.comment,
        'ImageId': value.imageId,
        'OsuExport': OsuExportImageExportTaskToJSON(value.osuExport),
        'Progress': value.progress,
        'State': value.state,
        'Tags': value.tags === undefined ? undefined : ((value.tags as Array<any>).map(ResourceTagToJSON)),
        'TaskId': value.taskId,
    };
}

