/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.20
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkNicRequest
 */
export interface LinkNicRequest {
    /**
     * The index of the VM device for the NIC attachment (between `1` and `7`, both included).
     * @type {number}
     * @memberof LinkNicRequest
     */
    deviceNumber: number;
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof LinkNicRequest
     */
    dryRun?: boolean;
    /**
     * The ID of the NIC you want to attach.
     * @type {string}
     * @memberof LinkNicRequest
     */
    nicId: string;
    /**
     * The ID of the VM to which you want to attach the NIC.
     * @type {string}
     * @memberof LinkNicRequest
     */
    vmId: string;
}

export function LinkNicRequestFromJSON(json: any): LinkNicRequest {
    return LinkNicRequestFromJSONTyped(json, false);
}

export function LinkNicRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkNicRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceNumber': json['DeviceNumber'],
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
        'nicId': json['NicId'],
        'vmId': json['VmId'],
    };
}

export function LinkNicRequestToJSON(value?: LinkNicRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DeviceNumber': value.deviceNumber,
        'DryRun': value.dryRun,
        'NicId': value.nicId,
        'VmId': value.vmId,
    };
}

