/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.24
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface LinkNicResponse
 */
export interface LinkNicResponse {
    /**
     * The ID of the NIC attachment.
     * @type {string}
     * @memberof LinkNicResponse
     */
    linkNicId?: string;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof LinkNicResponse
     */
    responseContext?: ModelResponseContext;
}

export function LinkNicResponseFromJSON(json: any): LinkNicResponse {
    return LinkNicResponseFromJSONTyped(json, false);
}

export function LinkNicResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkNicResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'linkNicId': !exists(json, 'LinkNicId') ? undefined : json['LinkNicId'],
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function LinkNicResponseToJSON(value?: LinkNicResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LinkNicId': value.linkNicId,
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

