/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.25
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClientGateway,
    ClientGatewayFromJSON,
    ClientGatewayFromJSONTyped,
    ClientGatewayToJSON,
} from './ClientGateway';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface ReadClientGatewaysResponse
 */
export interface ReadClientGatewaysResponse {
    /**
     * Information about one or more client gateways.
     * @type {Array<ClientGateway>}
     * @memberof ReadClientGatewaysResponse
     */
    clientGateways?: Array<ClientGateway>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadClientGatewaysResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadClientGatewaysResponseFromJSON(json: any): ReadClientGatewaysResponse {
    return ReadClientGatewaysResponseFromJSONTyped(json, false);
}

export function ReadClientGatewaysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadClientGatewaysResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientGateways': !exists(json, 'ClientGateways') ? undefined : ((json['ClientGateways'] as Array<any>).map(ClientGatewayFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadClientGatewaysResponseToJSON(value?: ReadClientGatewaysResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ClientGateways': value.clientGateways === undefined ? undefined : ((value.clientGateways as Array<any>).map(ClientGatewayToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

