/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';
import {
    Net,
    NetFromJSON,
    NetFromJSONTyped,
    NetToJSON,
} from './Net';

/**
 * 
 * @export
 * @interface ReadNetsResponse
 */
export interface ReadNetsResponse {
    /**
     * Information about the described Nets.
     * @type {Array<Net>}
     * @memberof ReadNetsResponse
     */
    nets?: Array<Net>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadNetsResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadNetsResponseFromJSON(json: any): ReadNetsResponse {
    return ReadNetsResponseFromJSONTyped(json, false);
}

export function ReadNetsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadNetsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nets': !exists(json, 'Nets') ? undefined : ((json['Nets'] as Array<any>).map(NetFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadNetsResponseToJSON(value?: ReadNetsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Nets': value.nets === undefined ? undefined : ((value.nets as Array<any>).map(NetToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

