/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LoadBalancer,
    LoadBalancerFromJSON,
    LoadBalancerFromJSONTyped,
    LoadBalancerToJSON,
} from './LoadBalancer';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface ReadLoadBalancersResponse
 */
export interface ReadLoadBalancersResponse {
    /**
     * Information about one or more load balancers.
     * @type {Array<LoadBalancer>}
     * @memberof ReadLoadBalancersResponse
     */
    loadBalancers?: Array<LoadBalancer>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadLoadBalancersResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadLoadBalancersResponseFromJSON(json: any): ReadLoadBalancersResponse {
    return ReadLoadBalancersResponseFromJSONTyped(json, false);
}

export function ReadLoadBalancersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadLoadBalancersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loadBalancers': !exists(json, 'LoadBalancers') ? undefined : ((json['LoadBalancers'] as Array<any>).map(LoadBalancerFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadLoadBalancersResponseToJSON(value?: ReadLoadBalancersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LoadBalancers': value.loadBalancers === undefined ? undefined : ((value.loadBalancers as Array<any>).map(LoadBalancerToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

