/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';
import {
    VmType,
    VmTypeFromJSON,
    VmTypeFromJSONTyped,
    VmTypeToJSON,
} from './VmType';

/**
 * 
 * @export
 * @interface ReadVmTypesResponse
 */
export interface ReadVmTypesResponse {
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadVmTypesResponse
     */
    responseContext?: ModelResponseContext;
    /**
     * Information about one or more VM types.
     * @type {Array<VmType>}
     * @memberof ReadVmTypesResponse
     */
    vmTypes?: Array<VmType>;
}

export function ReadVmTypesResponseFromJSON(json: any): ReadVmTypesResponse {
    return ReadVmTypesResponseFromJSONTyped(json, false);
}

export function ReadVmTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadVmTypesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
        'vmTypes': !exists(json, 'VmTypes') ? undefined : ((json['VmTypes'] as Array<any>).map(VmTypeFromJSON)),
    };
}

export function ReadVmTypesResponseToJSON(value?: ReadVmTypesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
        'VmTypes': value.vmTypes === undefined ? undefined : ((value.vmTypes as Array<any>).map(VmTypeToJSON)),
    };
}

