/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Keypair,
    KeypairFromJSON,
    KeypairFromJSONTyped,
    KeypairToJSON,
} from './Keypair';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface ReadKeypairsResponse
 */
export interface ReadKeypairsResponse {
    /**
     * Information about one or more keypairs.
     * @type {Array<Keypair>}
     * @memberof ReadKeypairsResponse
     */
    keypairs?: Array<Keypair>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadKeypairsResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadKeypairsResponseFromJSON(json: any): ReadKeypairsResponse {
    return ReadKeypairsResponseFromJSONTyped(json, false);
}

export function ReadKeypairsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadKeypairsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'keypairs': !exists(json, 'Keypairs') ? undefined : ((json['Keypairs'] as Array<any>).map(KeypairFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadKeypairsResponseToJSON(value?: ReadKeypairsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Keypairs': value.keypairs === undefined ? undefined : ((value.keypairs as Array<any>).map(KeypairToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

