/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FlexibleGpu,
    FlexibleGpuFromJSON,
    FlexibleGpuFromJSONTyped,
    FlexibleGpuToJSON,
} from './FlexibleGpu';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface ReadFlexibleGpusResponse
 */
export interface ReadFlexibleGpusResponse {
    /**
     * Information about one or more fGPUs.
     * @type {Array<FlexibleGpu>}
     * @memberof ReadFlexibleGpusResponse
     */
    flexibleGpus?: Array<FlexibleGpu>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadFlexibleGpusResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadFlexibleGpusResponseFromJSON(json: any): ReadFlexibleGpusResponse {
    return ReadFlexibleGpusResponseFromJSONTyped(json, false);
}

export function ReadFlexibleGpusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadFlexibleGpusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flexibleGpus': !exists(json, 'FlexibleGpus') ? undefined : ((json['FlexibleGpus'] as Array<any>).map(FlexibleGpuFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadFlexibleGpusResponseToJSON(value?: ReadFlexibleGpusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FlexibleGpus': value.flexibleGpus === undefined ? undefined : ((value.flexibleGpus as Array<any>).map(FlexibleGpuToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

