/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.25
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Image,
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';

/**
 * 
 * @export
 * @interface ReadImagesResponse
 */
export interface ReadImagesResponse {
    /**
     * Information about one or more OMIs.
     * @type {Array<Image>}
     * @memberof ReadImagesResponse
     */
    images?: Array<Image>;
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadImagesResponse
     */
    responseContext?: ModelResponseContext;
}

export function ReadImagesResponseFromJSON(json: any): ReadImagesResponse {
    return ReadImagesResponseFromJSONTyped(json, false);
}

export function ReadImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadImagesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'images': !exists(json, 'Images') ? undefined : ((json['Images'] as Array<any>).map(ImageFromJSON)),
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
    };
}

export function ReadImagesResponseToJSON(value?: ReadImagesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Images': value.images === undefined ? undefined : ((value.images as Array<any>).map(ImageToJSON)),
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
    };
}

