/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';
import {
    RouteTable,
    RouteTableFromJSON,
    RouteTableFromJSONTyped,
    RouteTableToJSON,
} from './RouteTable';

/**
 * 
 * @export
 * @interface ReadRouteTablesResponse
 */
export interface ReadRouteTablesResponse {
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof ReadRouteTablesResponse
     */
    responseContext?: ModelResponseContext;
    /**
     * Information about one or more route tables.
     * @type {Array<RouteTable>}
     * @memberof ReadRouteTablesResponse
     */
    routeTables?: Array<RouteTable>;
}

export function ReadRouteTablesResponseFromJSON(json: any): ReadRouteTablesResponse {
    return ReadRouteTablesResponseFromJSONTyped(json, false);
}

export function ReadRouteTablesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRouteTablesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
        'routeTables': !exists(json, 'RouteTables') ? undefined : ((json['RouteTables'] as Array<any>).map(RouteTableFromJSON)),
    };
}

export function ReadRouteTablesResponseToJSON(value?: ReadRouteTablesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
        'RouteTables': value.routeTables === undefined ? undefined : ((value.routeTables as Array<any>).map(RouteTableToJSON)),
    };
}

