/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResourceTag,
    ResourceTagFromJSON,
    ResourceTagFromJSONTyped,
    ResourceTagToJSON,
} from './ResourceTag';

/**
 * Information about the Subnet.
 * @export
 * @interface Subnet
 */
export interface Subnet {
    /**
     * The number of available IPs in the Subnets.
     * @type {number}
     * @memberof Subnet
     */
    availableIpsCount?: number;
    /**
     * The IP range in the Subnet, in CIDR notation (for example, 10.0.0.0/16).
     * @type {string}
     * @memberof Subnet
     */
    ipRange?: string;
    /**
     * If true, a public IP is assigned to the network interface cards (NICs) created in the specified Subnet.
     * @type {boolean}
     * @memberof Subnet
     */
    mapPublicIpOnLaunch?: boolean;
    /**
     * The ID of the Net in which the Subnet is.
     * @type {string}
     * @memberof Subnet
     */
    netId?: string;
    /**
     * The state of the Subnet (`pending` \| `available`).
     * @type {string}
     * @memberof Subnet
     */
    state?: string;
    /**
     * The ID of the Subnet.
     * @type {string}
     * @memberof Subnet
     */
    subnetId?: string;
    /**
     * The name of the Subregion in which the Subnet is located.
     * @type {string}
     * @memberof Subnet
     */
    subregionName?: string;
    /**
     * One or more tags associated with the Subnet.
     * @type {Array<ResourceTag>}
     * @memberof Subnet
     */
    tags?: Array<ResourceTag>;
}

export function SubnetFromJSON(json: any): Subnet {
    return SubnetFromJSONTyped(json, false);
}

export function SubnetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subnet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableIpsCount': !exists(json, 'AvailableIpsCount') ? undefined : json['AvailableIpsCount'],
        'ipRange': !exists(json, 'IpRange') ? undefined : json['IpRange'],
        'mapPublicIpOnLaunch': !exists(json, 'MapPublicIpOnLaunch') ? undefined : json['MapPublicIpOnLaunch'],
        'netId': !exists(json, 'NetId') ? undefined : json['NetId'],
        'state': !exists(json, 'State') ? undefined : json['State'],
        'subnetId': !exists(json, 'SubnetId') ? undefined : json['SubnetId'],
        'subregionName': !exists(json, 'SubregionName') ? undefined : json['SubregionName'],
        'tags': !exists(json, 'Tags') ? undefined : ((json['Tags'] as Array<any>).map(ResourceTagFromJSON)),
    };
}

export function SubnetToJSON(value?: Subnet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AvailableIpsCount': value.availableIpsCount,
        'IpRange': value.ipRange,
        'MapPublicIpOnLaunch': value.mapPublicIpOnLaunch,
        'NetId': value.netId,
        'State': value.state,
        'SubnetId': value.subnetId,
        'SubregionName': value.subregionName,
        'Tags': value.tags === undefined ? undefined : ((value.tags as Array<any>).map(ResourceTagToJSON)),
    };
}

