/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelResponseContext,
    ModelResponseContextFromJSON,
    ModelResponseContextFromJSONTyped,
    ModelResponseContextToJSON,
} from './ModelResponseContext';
import {
    Vm,
    VmFromJSON,
    VmFromJSONTyped,
    VmToJSON,
} from './Vm';

/**
 * 
 * @export
 * @interface UpdateVmResponse
 */
export interface UpdateVmResponse {
    /**
     * 
     * @type {ModelResponseContext}
     * @memberof UpdateVmResponse
     */
    responseContext?: ModelResponseContext;
    /**
     * 
     * @type {Vm}
     * @memberof UpdateVmResponse
     */
    vm?: Vm;
}

export function UpdateVmResponseFromJSON(json: any): UpdateVmResponse {
    return UpdateVmResponseFromJSONTyped(json, false);
}

export function UpdateVmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVmResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'responseContext': !exists(json, 'ResponseContext') ? undefined : ModelResponseContextFromJSON(json['ResponseContext']),
        'vm': !exists(json, 'Vm') ? undefined : VmFromJSON(json['Vm']),
    };
}

export function UpdateVmResponseToJSON(value?: UpdateVmResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseContext': ModelResponseContextToJSON(value.responseContext),
        'Vm': VmToJSON(value.vm),
    };
}

