/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PermissionsOnResourceCreation,
    PermissionsOnResourceCreationFromJSON,
    PermissionsOnResourceCreationFromJSONTyped,
    PermissionsOnResourceCreationToJSON,
} from './PermissionsOnResourceCreation';

/**
 * 
 * @export
 * @interface UpdateImageRequest
 */
export interface UpdateImageRequest {
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof UpdateImageRequest
     */
    dryRun?: boolean;
    /**
     * The ID of the OMI you want to modify.
     * @type {string}
     * @memberof UpdateImageRequest
     */
    imageId: string;
    /**
     * 
     * @type {PermissionsOnResourceCreation}
     * @memberof UpdateImageRequest
     */
    permissionsToLaunch: PermissionsOnResourceCreation;
}

export function UpdateImageRequestFromJSON(json: any): UpdateImageRequest {
    return UpdateImageRequestFromJSONTyped(json, false);
}

export function UpdateImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateImageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
        'imageId': json['ImageId'],
        'permissionsToLaunch': PermissionsOnResourceCreationFromJSON(json['PermissionsToLaunch']),
    };
}

export function UpdateImageRequestToJSON(value?: UpdateImageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DryRun': value.dryRun,
        'ImageId': value.imageId,
        'PermissionsToLaunch': PermissionsOnResourceCreationToJSON(value.permissionsToLaunch),
    };
}

