/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /><br />  The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br />  Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but some resources have different names in AWS than in the OUTSCALE API. You can find a list of the differences [here](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html).<br /><br />  You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.
 *
 * The version of the OpenAPI document: 1.19
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRoutePropagationRequest
 */
export interface UpdateRoutePropagationRequest {
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof UpdateRoutePropagationRequest
     */
    dryRun?: boolean;
    /**
     * If true, a virtual gateway can propagate routes to a specified route table of a Net. If false, the propagation is disabled.
     * @type {boolean}
     * @memberof UpdateRoutePropagationRequest
     */
    enable: boolean;
    /**
     * The ID of the route table.
     * @type {string}
     * @memberof UpdateRoutePropagationRequest
     */
    routeTableId: string;
    /**
     * The ID of the virtual gateway.
     * @type {string}
     * @memberof UpdateRoutePropagationRequest
     */
    virtualGatewayId: string;
}

export function UpdateRoutePropagationRequestFromJSON(json: any): UpdateRoutePropagationRequest {
    return UpdateRoutePropagationRequestFromJSONTyped(json, false);
}

export function UpdateRoutePropagationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoutePropagationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
        'enable': json['Enable'],
        'routeTableId': json['RouteTableId'],
        'virtualGatewayId': json['VirtualGatewayId'],
    };
}

export function UpdateRoutePropagationRequestToJSON(value?: UpdateRoutePropagationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DryRun': value.dryRun,
        'Enable': value.enable,
        'RouteTableId': value.routeTableId,
        'VirtualGatewayId': value.virtualGatewayId,
    };
}

