/* tslint:disable */
/* eslint-disable */
/**
 * 3DS OUTSCALE API
 * Welcome to the OUTSCALE API documentation.<br /> The OUTSCALE API enables you to manage your resources in the OUTSCALE Cloud. This documentation describes the different actions available along with code examples.<br /><br /> You can learn more about errors returned by the API in the dedicated [errors page](api/errors).<br /><br /> Note that the OUTSCALE Cloud is compatible with Amazon Web Services (AWS) APIs, but there are [differences in resource names](https://docs.outscale.com/en/userguide/OUTSCALE-APIs-Reference.html) between AWS and the OUTSCALE API.<br /> You can also manage your resources using the [Cockpit](https://docs.outscale.com/en/userguide/About-Cockpit.html) web interface.<br /><br /> An OpenAPI description of the OUTSCALE API is also available in this [GitHub repository](https://github.com/outscale/osc-api).
 *
 * The version of the OpenAPI document: 1.26
 * Contact: support@outscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LinkNicToUpdate,
    LinkNicToUpdateFromJSON,
    LinkNicToUpdateFromJSONTyped,
    LinkNicToUpdateToJSON,
} from './LinkNicToUpdate';

/**
 * 
 * @export
 * @interface UpdateNicRequest
 */
export interface UpdateNicRequest {
    /**
     * A new description for the NIC.
     * @type {string}
     * @memberof UpdateNicRequest
     */
    description?: string;
    /**
     * If true, checks whether you have the required permissions to perform the action.
     * @type {boolean}
     * @memberof UpdateNicRequest
     */
    dryRun?: boolean;
    /**
     * 
     * @type {LinkNicToUpdate}
     * @memberof UpdateNicRequest
     */
    linkNic?: LinkNicToUpdate;
    /**
     * The ID of the NIC you want to modify.
     * @type {string}
     * @memberof UpdateNicRequest
     */
    nicId: string;
    /**
     * One or more IDs of security groups for the NIC.<br />
     * You must specify at least one group, even if you use the default security group in the Net.
     * @type {Array<string>}
     * @memberof UpdateNicRequest
     */
    securityGroupIds?: Array<string>;
}

export function UpdateNicRequestFromJSON(json: any): UpdateNicRequest {
    return UpdateNicRequestFromJSONTyped(json, false);
}

export function UpdateNicRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNicRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'Description') ? undefined : json['Description'],
        'dryRun': !exists(json, 'DryRun') ? undefined : json['DryRun'],
        'linkNic': !exists(json, 'LinkNic') ? undefined : LinkNicToUpdateFromJSON(json['LinkNic']),
        'nicId': json['NicId'],
        'securityGroupIds': !exists(json, 'SecurityGroupIds') ? undefined : json['SecurityGroupIds'],
    };
}

export function UpdateNicRequestToJSON(value?: UpdateNicRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Description': value.description,
        'DryRun': value.dryRun,
        'LinkNic': LinkNicToUpdateToJSON(value.linkNic),
        'NicId': value.nicId,
        'SecurityGroupIds': value.securityGroupIds,
    };
}

