name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Publish on NPM
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_OSC_SDK_JS }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        cd packages/osc-sdk-js
        bun install --frozen-lockfile 
        bun run build
        bun publish
